# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal info
name: Franck Garcia
title: Senior Java Developper
email: garcia.franck@gmail.com 
website: garcimouche.github.io

# Social links
twitter_username: franck_garcia
github_username:  garcimouche
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: franck-garcia-2a602b10
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# stack overflow?
additional_links:
        - url: https://stackoverflow.com/users/756146/franck
          icon: fa-stack-overflow
          title: stack overflow

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a software developer/architect with an extensive experience of the Java ecosystem. 
  Improving and learning new skills by following the latest technological trends is one of my constant concern. 
  Over the years, the various mandates I worked on have enabled me to reveal my skills in the realization of innovative quality solutions.
  
  I am most skilled in: <mark>Java</mark><mark>Jave EE</mark>

# Projects Section
# projects_title: ojects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
